site_name: "Taller de React con TypeScript"
site_author: "Sergio Gómez <sergio@uco.es>"
site_description: "Taller de introducción a React con TypeScript"
repo_name: "aulasoftwarelibre/taller-de-react-con-typescript"
repo_url: "https://github.com/aulasoftwarelibre/taller-de-react-con-typescript.git"

theme:
  name: "material"
  language: "es"
  favicon: "images/logoasl.png"

extra_css: [extra.css]
extra:
  palette:
    primary: "green"
    accent: "light green"
  social:
    - type: "github"
      link: "https://github.com/aulasoftwarelibre"
    - type: "twitter"
      link: "https://twitter.com/aulasl"
    - type: "facebook"
      link: "https://facebook.com/aulasl"
    - type: "instagram"
      link: "https://instagram.com/aulasoftwarelibre"
  feature:
    tabs: true

markdown_extensions:
  - admonition: ~
  - attr_list: ~
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list: ~
  - footnotes: ~
  - toc:
      permalink: true

google_analytics:
  - "UA-51754922-1"
  - "auto"

nav:
  - Inicio: index.md
  - Instalación: installation.md
